This is 4 variable linear regresion using linear algebra equation

In [2]:
# Numpy for linear algebra
import numpy as np

# Matplotlib for plotting
import matplotlib.pyplot as plt

In [3]:
# Creating random dataframe/matrix with correlation
datapoints = 20

# Creating vectors of random points with some noise
x = np.array([i + np.random.randint(7) for i in np.linspace(1, 10, datapoints)], dtype='i4')
h = np.array([i + np.random.randint(4) for i in np.linspace(23, 60, datapoints)], dtype='i4')
g = np.array([i + np.random.randint(13) for i in np.linspace(500, 870, datapoints)], dtype='i4')
z = np.array([i + np.random.randint(7) for i in np.linspace(14, 25, datapoints)], dtype='i4')

y = np.linspace(1200, 20000, datapoints) # target

# Creating matrix
X = np.vstack([x,h,g,z]).T
X

array([[  2,  25, 503,  19],
       [  7,  27, 527,  20],
       [  3,  26, 541,  19],
       [  5,  31, 566,  16],
       [  4,  32, 579,  19],
       [  5,  32, 606,  16],
       [  8,  35, 616,  19],
       [  8,  39, 639,  20],
       [ 10,  40, 659,  20],
       [  6,  40, 679,  20],
       [  5,  43, 698,  25],
       [ 10,  47, 717,  22],
       [  6,  46, 734,  20],
       [  7,  48, 762,  27],
       [ 12,  51, 774,  26],
       [  8,  52, 795,  24],
       [ 13,  55, 815,  28],
       [ 11,  58, 834,  25],
       [ 10,  61, 861,  24],
       [ 16,  61, 882,  29]])

In [4]:
# Algorythm
result = np.linalg.inv(X.T @ X) @ X.T @ y
result

array([-99.61820836, 897.14220027, -38.45142016,  -7.23174554])

In [5]:
# Results in hyperplane
X @ result

array([ 2750.85108236,  3116.97861161,  2087.22110804,  5434.10542518,
        5909.30213508,  4793.1908189 ,  6779.55335637,  9476.50774815,
        9405.38512841,  9034.82955859, 11059.13865697, 13440.73466973,
       12302.8546512 , 12870.25886003, 14609.4091226 , 15112.00782396,
       16507.38799752, 18689.16926857, 20449.25747886, 19007.90967754])